#!/bin/bash
# Clean results that will be regenerated by REPRODUCIBILITY.md pipeline

echo "=== Cleaning results directories that will be regenerated ==="

# Remove old training results (will be regenerated)
echo "Removing old training results..."
rm -rf results/full_training/*
rm -rf results/hyperopt/*

# Remove old test evaluation (will be regenerated)
echo "Removing old test evaluation..."
rm -rf results/test_evaluation/*

# Keep validation_predictions aggregated TSV, remove individual directories
echo "Cleaning validation predictions (keeping aggregated TSV)..."
find results/validation_predictions/ -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
# Keep validation_predictions.tsv if it exists

# Remove old training logs
echo "Removing old training logs..."
rm -rf logs/final_training/*
rm -rf logs/multitask/*

echo ""
echo "✓ Cleanup complete!"
echo ""
echo "Directories cleaned:"
echo "  - results/full_training/"
echo "  - results/hyperopt/"
echo "  - results/test_evaluation/"
echo "  - results/validation_predictions/ (subdirectories only)"
echo "  - logs/final_training/"
echo "  - logs/multitask/"
echo ""
echo "Next: Run REPRODUCIBILITY.md pipeline from scratch"
