#!/usr/bin/env python3
"""
Download missing unitig files from Logan S3 bucket.

Identifies missing unitig files needed for v7 splits (train + test sets)
and generates download commands for AWS CLI or wget.

Usage:
    python scripts/downloads/01_download_missing_unitigs.py --output scripts/downloads/download_unitigs.sh
    bash scripts/downloads/download_unitigs.sh
    
    # Or submit as SLURM array job
    sbatch scripts/downloads/02_download_unitigs.sbatch
"""

import argparse
from pathlib import Path


def load_accessions(split_dir: Path) -> set:
    """Load train and test accessions from v7 splits."""
    accessions = set()
    
    for split_file in ['train_accessions.txt', 'test_accessions.txt']:
        file_path = split_dir / split_file
        if file_path.exists():
            with open(file_path) as f:
                accessions.update(line.strip() for line in f if line.strip())
    
    return accessions


def find_existing_unitigs(unitig_dir: Path) -> set:
    """Find existing unitig files (both .gz and .zst formats)."""
    existing = set()
    
    if unitig_dir.exists():
        # Check for .gz files (already converted)
        for gz_file in unitig_dir.glob('*.gz'):
            accession = gz_file.stem.replace('.unitigs.fa', '')
            existing.add(accession)
        
        # Check for .zst files (downloaded but not converted)
        for zst_file in unitig_dir.glob('*.zst'):
            accession = zst_file.stem.replace('.unitigs.fa', '')
            existing.add(accession)
    
    return existing


def main():
    parser = argparse.ArgumentParser(description='Generate download script for missing unitig files')
    parser.add_argument('--splits', type=Path, default=Path('data/splits_v7'),
                        help='Directory containing v7 split files')
    parser.add_argument('--unitigs', type=Path, default=Path('data/unitigs'),
                        help='Directory containing existing unitig files')
    parser.add_argument('--output', type=Path, default=Path('scripts/downloads/download_unitigs.sh'),
                        help='Output bash script')
    parser.add_argument('--accession-list', type=Path, default=Path('scripts/downloads/missing_unitigs.txt'),
                        help='Output list of missing accessions')
    args = parser.parse_args()
    
    # Create output directory
    args.output.parent.mkdir(parents=True, exist_ok=True)
    
    # Load required accessions (train + test)
    print("Loading accessions from v7 splits...")
    required = load_accessions(args.splits)
    print(f"  Required: {len(required)} accessions (train + test)")
    
    # Find existing unitigs
    print("\nChecking existing unitig files...")
    existing = find_existing_unitigs(args.unitigs)
    print(f"  Existing: {len(existing)} unitig files")
    
    # Identify missing
    missing = sorted(required - existing)
    print(f"  Missing:  {len(missing)} unitig files")
    
    if not missing:
        print("\n✓ All unitig files are available!")
        return
    
    # Write missing accessions list
    with open(args.accession_list, 'w') as f:
        f.write('\n'.join(missing) + '\n')
    print(f"\n✓ Wrote missing accessions to {args.accession_list}")
    
    # Generate download script
    with open(args.output, 'w') as f:
        f.write('#!/bin/bash\n')
        f.write('# Auto-generated script to download missing unitig files from Logan\n')
        f.write(f'# Total files to download: {len(missing)}\n')
        f.write('# Generated by: scripts/downloads/01_download_missing_unitigs.py\n\n')
        f.write('set -euo pipefail\n\n')
        f.write('UNITIG_DIR="data/unitigs"\n')
        f.write('mkdir -p "$UNITIG_DIR"\n')
        f.write('cd "$UNITIG_DIR"\n\n')
        f.write('# Download function with retry logic\n')
        f.write('download_unitig() {\n')
        f.write('    local accession=$1\n')
        f.write('    local url="s3://logan-pub/u/${accession}/${accession}.unitigs.fa.zst"\n')
        f.write('    local output="${accession}.unitigs.fa.zst"\n')
        f.write('    \n')
        f.write('    # Skip if already downloaded\n')
        f.write('    if [ -f "$output" ] || [ -f "${accession}.unitigs.fa.gz" ]; then\n')
        f.write('        echo "✓ Skip $accession (already exists)"\n')
        f.write('        return 0\n')
        f.write('    fi\n')
        f.write('    \n')
        f.write('    echo "Downloading $accession..."\n')
        f.write('    if aws s3 cp "$url" . --no-sign-request; then\n')
        f.write('        echo "✓ Downloaded $accession"\n')
        f.write('    else\n')
        f.write('        echo "✗ Failed to download $accession" >&2\n')
        f.write('        return 1\n')
        f.write('    fi\n')
        f.write('}\n\n')
        f.write('export -f download_unitig\n\n')
        f.write('# Download all missing files\n')
        f.write(f'echo "Downloading {len(missing)} missing unitig files..."\n\n')
        
        for acc in missing:
            f.write(f'download_unitig {acc}\n')
        
        f.write(f'\necho "\\n✓ Download complete!"\n')
    
    args.output.chmod(0o755)
    print(f"✓ Wrote download script to {args.output}")
    print(f"\nTo download sequentially:\n  bash {args.output}")
    print(f"\nTo download in parallel using GNU parallel (faster):")
    print(f"  parallel -j 8 --bar 'aws s3 cp s3://logan-pub/u/{{}}/{{}}.unitigs.fa.zst data/unitigs/ --no-sign-request' :::: {args.accession_list}")
    print(f"\nOr submit as SLURM array job:")
    print(f"  sbatch --array=1-{len(missing)}%50 scripts/downloads/02_download_unitigs.sbatch")


if __name__ == '__main__':
    main()
