#!/usr/bin/env python3
"""
Single-sample confidence visualisation (diana-predict style).

Reproduces the four-panel bar-chart output generated by diana-predict's
04_plot_results.py, one sub-plot per task.  The predicted class bar is
highlighted; bars for the true class are marked with ★ when the prediction
differs; correctly predicted classes are marked ✓.

USAGE:
    python scripts/paper/33_plot_single_sample_confidence.py \\
        --sample ERR11413727 [--sample SRR4027589 ...]

OUTPUT:
    paper/figures/final/sample_{SID}_confidence.png/.html
"""

import argparse
import json
import sys
from pathlib import Path

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from config import PATHS, PLOT_CONFIG, TASKS

VAL_PRED_DIR = Path(PATHS["predictions_dir"])   # results/validation_predictions_bioproject
VAL_META     = Path(PATHS["validation_metadata"])
FIGURES_DIR  = Path(PATHS["figures_dir"])

TASK_LABELS = {
    "sample_type":    "Sample Type",
    "community_type": "Community Type",
    "sample_host":    "Sample Host",
    "material":       "Material",
}

# Colour per task — same Vivid palette used everywhere else in the paper
VIVID = PLOT_CONFIG["colors"]["palette"]
TASK_COLORS = {
    "sample_type":    VIVID[0],
    "community_type": VIVID[1],
    "sample_host":    VIVID[2],
    "material":       VIVID[3],
}
WRONG_COLOR    = "#e74c3c"   # red bar when prediction is wrong
GREY_COLOR     = "#cccccc"   # other classes


def load_sample(sid: str) -> tuple[dict, dict]:
    """Return (predictions_dict, true_labels_dict) for one sample."""
    fpath = VAL_PRED_DIR / sid / f"{sid}_predictions.json"
    if not fpath.exists():
        sys.exit(f"Prediction file not found: {fpath}")
    with open(fpath) as f:
        data = json.load(f)

    meta = pd.read_csv(VAL_META, sep="\t")
    row  = meta[meta["Run_accession"] == sid]
    if row.empty:
        sys.exit(f"Sample {sid} not found in validation metadata.")
    r = row.iloc[0]
    true_labels = {t: str(r.get(t, "")) for t in TASKS}
    return data["predictions"], true_labels


def build_figure(sid: str, predictions: dict, true_labels: dict) -> go.Figure:
    """Build a 4-panel figure matching diana-predict's 04_plot_results.py style.

    Layout:
      - One sub-plot per task (2 × 2 grid).
      - Bars are vertical, x-axis = class names (rotated 45°), y = probability.
      - Predicted class highlighted with task colour (red if wrong).
      - True class bar annotated with ★ when it differs from the prediction.
    """
    border  = PLOT_CONFIG["border_color"]
    font_sz = PLOT_CONFIG["font_size"]

    fig = make_subplots(
        rows=2, cols=2,
        subplot_titles=[TASK_LABELS[t] for t in TASKS],
        vertical_spacing=0.22,
        horizontal_spacing=0.10,
    )
    grid = [(1, 1), (1, 2), (2, 1), (2, 2)]

    for idx, task in enumerate(TASKS):
        row, col = grid[idx]
        if task not in predictions:
            continue

        task_pred  = predictions[task]
        pred_class = task_pred["predicted_class"]
        true_class = true_labels.get(task, "")
        confidence = task_pred.get("confidence", 0.0)
        probs      = task_pred["probabilities"]

        correct = (pred_class == true_class)

        # Sort by probability descending
        items   = sorted(probs.items(), key=lambda kv: kv[1], reverse=True)
        classes = [kv[0] for kv in items]
        values  = [kv[1] for kv in items]

        # Build x-tick labels  (★ for true class when different; ✓ for correct pred)
        x_labels = []
        for cls in classes:
            if cls == pred_class and cls == true_class:
                x_labels.append(f"✓ {cls}")
            elif cls == true_class and cls != pred_class:
                x_labels.append(f"★ {cls}")
            else:
                x_labels.append(cls)

        # Bar colours
        task_color = TASK_COLORS[task]
        bar_colors = []
        for cls in classes:
            if cls == pred_class:
                bar_colors.append(task_color if correct else WRONG_COLOR)
            else:
                bar_colors.append(GREY_COLOR)

        text_vals = [f"{v:.3f}" for v in values]

        subtitle = (
            f"Predicted: <b>{pred_class}</b>  "
            f"(conf: {confidence:.3f})  "
            f"{'✓' if correct else '✗ true: ' + true_class}"
        )

        fig.add_trace(
            go.Bar(
                x=x_labels,
                y=values,
                marker_color=bar_colors,
                marker_line=dict(color=border, width=0.6),
                text=text_vals,
                textposition="outside",
                cliponaxis=False,
                hovertemplate="<b>%{x}</b><br>Probability: %{y:.4f}<extra></extra>",
                showlegend=False,
                name=subtitle,
            ),
            row=row, col=col,
        )

        fig.update_xaxes(
            tickangle=-45,
            linecolor=border, linewidth=1,
            row=row, col=col,
        )
        fig.update_yaxes(
            range=[0, 1.15],
            title_text="Predicted Probability",
            linecolor=border, linewidth=1,
            gridcolor="#eeeeee",
            row=row, col=col,
        )

        # Per-panel annotation (subtitle below title)
        fig.layout.annotations[idx].update(
            text=f"{TASK_LABELS[task]}<br><sup>{subtitle}</sup>",
        )

    fig.update_layout(
        template="plotly_white",
        title=dict(
            text=f"DIANA — Sample <b>{sid}</b><br>"
                 f"<span style='font-size:10px; color:#666'>"
                 f"✓ = correct prediction  |  ★ = true class when prediction differs  |  "
                 f"red bar = wrong prediction</span>",
            font=dict(size=13), x=0.5, xanchor="center",
        ),
        font=dict(size=font_sz),
        width=1200,
        height=900,
        margin=dict(l=60, r=40, t=110, b=60),
    )
    return fig


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--sample", nargs="+",
        default=["ERR11413727", "SRR4027589"],
        help="One or more Run accession IDs to visualise",
    )
    args = parser.parse_args()

    FIGURES_DIR.mkdir(parents=True, exist_ok=True)

    for sid in args.sample:
        print(f"\n{'='*60}")
        print(f"Sample: {sid}")
        predictions, true_labels = load_sample(sid)

        print(f"  {'Task':<18} {'True':<32} {'Predicted':<32} {'Conf':>6}  {'OK?'}")
        print("  " + "-" * 95)
        for task in TASKS:
            pred = predictions.get(task, {}).get("predicted_class", "?")
            true = true_labels.get(task, "?")
            conf = predictions.get(task, {}).get("confidence", float("nan"))
            match = "✓" if pred == true else "✗"
            print(f"  {TASK_LABELS[task]:<18} {true:<32} {pred:<32} {conf:>6.4f}  {match}")

        fig = build_figure(sid, predictions, true_labels)
        out_base = FIGURES_DIR / f"sample_{sid}_confidence"
        fig.write_html(str(out_base.with_suffix(".html")))
        fig.write_image(str(out_base.with_suffix(".png")), scale=2)
        print(f"  → {out_base}.png")


if __name__ == "__main__":
    main()
