#!/usr/bin/env python3
"""
DIANA Project: Project samples onto reference PCA space.

This command visualizes where diana-predict samples fall in PCA space relative to 
training data. It uses the unitig fraction files already generated by diana-predict.

Usage:
    # Single sample
    diana-project --sample results/validation_predictions/ERR10114862/
    
    # Multiple samples
    diana-project --sample results/validation_predictions/ERR*/
"""

import argparse
import importlib.metadata
import logging
import sys
from pathlib import Path
import json
from glob import glob
import subprocess
import tempfile
import os
import plotly.graph_objects as go
import plotly.express as px
import numpy as np
import pickle

logger = logging.getLogger(__name__)


def setup_logging(verbose=False):
    """Setup logging configuration."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )


def load_sample_from_prediction_dir(prediction_dir: Path) -> tuple[np.ndarray, str]:
    """
    Load unitig fraction vector from a diana-predict output directory.
    
    Args:
        prediction_dir: Path to diana-predict output directory
        
    Returns:
        (unitig_vector, sample_id)
    """
    prediction_dir = Path(prediction_dir)
    sample_id = prediction_dir.name
    
    # Find unitig fraction file
    unitig_fraction_file = prediction_dir / f"{sample_id}_unitig_fraction.txt"
    
    if not unitig_fraction_file.exists():
        raise FileNotFoundError(
            f"Unitig fraction file not found: {unitig_fraction_file}\n"
            f"Expected: {sample_id}_unitig_fraction.txt\n"
            f"This sample may not have been processed by diana-predict yet."
        )
    
    logger.info(f"Loading sample: {sample_id}")
    logger.debug(f"  From: {unitig_fraction_file}")
    
    # Load vector
    unitig_vector = np.loadtxt(unitig_fraction_file)
    logger.debug(f"  Vector shape: {unitig_vector.shape}")
    
    return unitig_vector, sample_id


def load_pca_reference(pca_reference_path: Path):
    """Load saved PCA model and reference data."""
    if not pca_reference_path.exists():
        logger.error(f"PCA reference not found: {pca_reference_path}")
        logger.error("")
        logger.error("Please generate PCA reference first:")
        logger.error("  python scripts/paper/06_generate_pca_analysis.py")
        raise FileNotFoundError(f"PCA reference not found: {pca_reference_path}")
    
    logger.info(f"Loading PCA reference: {pca_reference_path}")
    
    with open(pca_reference_path, 'rb') as f:
        reference_data = pickle.load(f)
    
    logger.info(f"  ✓ PCA components: {reference_data['pca_model'].n_components_}")
    logger.info(f"  ✓ Reference samples: {len(reference_data['sample_ids'])}")
    logger.info(f"  ✓ Features: {reference_data['n_features']} unitigs")
    
    return reference_data


def project_sample(unitig_vector: np.ndarray, reference_data: dict, sample_id: str):
    """Project sample onto reference PCA space."""
    logger.info(f"Projecting {sample_id} onto reference PCA space...")
    
    # Validate dimensions match
    if unitig_vector.shape[0] != reference_data['n_features']:
        raise ValueError(
            f"Feature dimension mismatch: sample has {unitig_vector.shape[0]} features, "
            f"reference expects {reference_data['n_features']}"
        )
    
    # Reshape to (1, n_features)
    sample_matrix = unitig_vector.reshape(1, -1)
    
    # Apply standardization if reference was standardized
    if reference_data.get('standardized', False) and 'scaler' in reference_data:
        logger.debug("  Applying standardization...")
        sample_matrix = reference_data['scaler'].transform(sample_matrix)
    
    # Project onto PCA space
    sample_pca = reference_data['pca_model'].transform(sample_matrix)
    logger.info(f"  ✓ Projected to {sample_pca.shape[1]}D PCA space")
    
    return sample_pca


def compute_neighbors(sample_pca, reference_pca, reference_sample_ids, k=5):
    """Find k nearest neighbors in PCA space."""
    from scipy.spatial.distance import cdist
    
    distances = cdist(sample_pca, reference_pca, metric='euclidean')[0]
    nearest_indices = np.argsort(distances)[:k]
    nearest_ids = [reference_sample_ids[i] for i in nearest_indices]
    nearest_distances = distances[nearest_indices]
    
    return nearest_ids, nearest_distances


def load_predictions(prediction_dir: Path):
    """Load diana-predict predictions if available."""
    prediction_file = prediction_dir / f"{prediction_dir.name}_predictions.json"
    
    if not prediction_file.exists():
        return None
    
    with open(prediction_file, 'r') as f:
        data = json.load(f)
    
    # Extract predictions in simplified format
    predictions = {}
    if 'predictions' in data:
        for task, task_data in data['predictions'].items():
            predictions[task] = {
                'label': task_data.get('predicted_class', 'Unknown'),
                'confidence': task_data.get('confidence', 0.0)
            }
    
    return predictions


def plot_pca_projection(
    sample_pca, 
    sample_id, 
    reference_pca, 
    reference_sample_ids,
    reference_metadata,
    output_dir: Path,
    nearest_ids=None,
    predictions=None
):
    """Create interactive PCA plot showing new sample and reference."""
    logger.info("Generating PCA projection plots...")
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create plots for each task
    tasks = ['sample_type', 'material', 'sample_host', 'community_type']
    
    for task in tasks:
        logger.info(f"  Creating plot for {task}...")
        
        fig = go.Figure()
        
        # Build a sample_id → label lookup so that ref_labels is aligned
        # with reference_sample_ids (PKL order), not with metadata sort order.
        try:
            ids_col = reference_metadata['Run_accession'].to_list()
            lbl_col = reference_metadata[task].to_list()
        except AttributeError:
            ids_col = reference_metadata['Run_accession'].tolist()
            lbl_col = reference_metadata[task].tolist()

        label_by_id = dict(zip(ids_col, lbl_col))
        ref_labels = np.array([label_by_id.get(sid, 'Unknown') for sid in reference_sample_ids])
        unique_labels = sorted(list(set(ref_labels)))
        
        for label in unique_labels:
            mask = ref_labels == label
            indices = np.where(mask)[0]
            
            fig.add_trace(go.Scatter(
                x=reference_pca[indices, 0],
                y=reference_pca[indices, 1],
                mode='markers',
                name=label,
                marker=dict(size=5, opacity=0.6),
                text=[reference_sample_ids[i] for i in indices],
                hovertemplate='<b>%{text}</b><br>PC1: %{x:.2f}<br>PC2: %{y:.2f}<extra></extra>'
            ))
        
        # Highlight nearest neighbors if provided
        if nearest_ids:
            neighbor_indices = [i for i, sid in enumerate(reference_sample_ids) if sid in nearest_ids]
            # Get labels for nearest neighbors
            neighbor_labels = [ref_labels[i] for i in neighbor_indices]
            hover_texts = [
                f'<b>{reference_sample_ids[i]}</b><br>{task}: {ref_labels[i]}<br>PC1: {{x:.2f}}<br>PC2: {{y:.2f}}'
                for i in neighbor_indices
            ]
            fig.add_trace(go.Scatter(
                x=reference_pca[neighbor_indices, 0],
                y=reference_pca[neighbor_indices, 1],
                mode='markers',
                name='Nearest Neighbors',
                marker=dict(
                    size=12,
                    color='yellow',
                    symbol='diamond',
                    line=dict(width=2, color='black')
                ),
                text=[reference_sample_ids[i] for i in neighbor_indices],
                customdata=neighbor_labels,
                hovertemplate='<b>%{text}</b><br>' + task.replace('_', ' ').title() + ': %{customdata}<br>PC1: %{x:.2f}<br>PC2: %{y:.2f}<extra></extra>'
            ))
        
        # Plot new sample
        hover_text = f'<b>{sample_id}</b><br>PC1: %{{x:.2f}}<br>PC2: %{{y:.2f}}'
        if predictions and task in predictions:
            pred_label = predictions[task]['label']
            pred_conf = predictions[task]['confidence']
            hover_text += f'<br>Predicted: {pred_label} ({pred_conf:.1%})'
        hover_text += '<extra></extra>'
        
        fig.add_trace(go.Scatter(
            x=sample_pca[:, 0],
            y=sample_pca[:, 1],
            mode='markers',
            name=f'New Sample: {sample_id}',
            marker=dict(
                size=15,
                color='red',
                symbol='star',
                line=dict(width=2, color='black')
            ),
            hovertemplate=hover_text
        ))
        
        # Add title with prediction if available
        title = f'PCA Projection - {task.replace("_", " ").title()}'
        if predictions and task in predictions:
            pred_label = predictions[task]['label']
            pred_conf = predictions[task]['confidence']
            title += f'<br><sub>Predicted: {pred_label} (confidence: {pred_conf:.1%})</sub>'
        
        fig.update_layout(
            title=title,
            xaxis_title='PC1',
            yaxis_title='PC2',
            template='plotly_white',
            hovermode='closest',
            legend=dict(
                yanchor="top",
                y=0.99,
                xanchor="left",
                x=0.01,
                bgcolor="rgba(255,255,255,0.8)"
            ),
            width=1000,
            height=800
        )
        
        # Save
        html_path = output_dir / f'pca_projection_{task}.html'
        png_path = output_dir / f'pca_projection_{task}.png'
        fig.write_html(str(html_path))
        try:
            fig.write_image(str(png_path), width=1400, height=1000)
            logger.info(f"    ✓ Saved: {html_path.name}, {png_path.name}")
        except Exception as e:
            logger.info(f"    ✓ Saved: {html_path.name}")
            if 'kaleido' in str(e).lower():
                logger.debug(f"    (PNG export requires kaleido package)")


def resolve_taxids(taxids, n_threads=None):
    """Resolve taxids to full lineages using taxonkit.
    
    Args:
        taxids: Array-like of taxid strings
        n_threads: Number of threads (default: from OMP_NUM_THREADS env var)
    
    Returns:
        dict mapping taxid (str) -> lineage (str)
    """
    taxid_to_lineage = {}
    temp_input = None
    
    try:
        # Create temp file with taxids
        temp_input = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt')
        for taxid in taxids:
            temp_input.write(f"{taxid}\n")
        temp_input.close()
        
        # Get number of threads
        if n_threads is None:
            n_threads = os.environ.get('OMP_NUM_THREADS', '16')
        
        # Run taxonkit
        cmd = (
            f'bash -c "module load taxonkit/ && '
            f'cat {temp_input.name} | '
            f'taxonkit lineage -i 1 -j {n_threads} '
            f'2>/dev/null"'
        )
        
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=300)
        
        if result.returncode == 0 and result.stdout.strip():
            for line in result.stdout.strip().split('\n'):
                if not line:
                    continue
                fields = line.split('\t')
                if len(fields) >= 2:
                    taxid = fields[0]
                    lineage = fields[1]
                    # Remove 'cellular organisms;' prefix
                    if lineage.startswith('cellular organisms;'):
                        lineage = lineage.replace('cellular organisms;', '', 1)
                    taxid_to_lineage[taxid] = lineage
        
        # Cleanup
        if temp_input and os.path.exists(temp_input.name):
            os.unlink(temp_input.name)
            
    except Exception as e:
        logger.warning(f"  Error running taxonkit: {e}")
        if temp_input and os.path.exists(temp_input.name):
            os.unlink(temp_input.name)
    
    return taxid_to_lineage


def extract_species_from_lineage(lineage):
    """Extract species name from semicolon-separated lineage."""
    if not lineage or lineage == 'Unknown':
        return 'Unknown'
    
    ranks = lineage.split(';')
    # Species is typically the last element
    species = ranks[-1].strip() if ranks else 'Unknown'
    
    # Clean up common artifacts
    if not species or species.lower() in ['', 'unknown', 'unclassified']:
        # Try genus (second to last)
        if len(ranks) >= 2:
            species = ranks[-2].strip()
    
    return species if species else 'Unknown'


def load_blast_annotations(blast_file: Path, unitig_ids):
    """Load BLAST annotations with taxids."""
    logger.info(f"\nLoading BLAST annotations from {blast_file.name}...")
    
    if not blast_file.exists():
        logger.warning(f"  BLAST file not found: {blast_file}")
        return None
    
    try:
        import polars as pl
        
        # Read raw BLAST format: columns 1=unitig_id, 13=taxid, 14=description
        blast_df = pl.read_csv(
            blast_file,
            separator="\t",
            has_header=False,
            new_columns=[
                'unitig_id', 'subject_id', 'pident', 'length', 'mismatch', 'gapopen',
                'qstart', 'qend', 'sstart', 'send', 'evalue', 'bitscore', 'taxid', 'description'
            ],
            schema_overrides={'taxid': pl.Utf8, 'unitig_id': pl.Int64}
        )
        
        logger.info(f"  ✓ Loaded {len(blast_df):,} BLAST hits")
        
        # Filter to unitigs in reference
        unitig_list = unitig_ids if isinstance(unitig_ids, list) else unitig_ids.tolist()
        blast_df = blast_df.filter(pl.col('unitig_id').is_in(unitig_list))
        logger.info(f"  ✓ {len(blast_df):,} hits match reference unitigs")
        
        return blast_df
        
    except Exception as e:
        logger.error(f"  Failed to load BLAST annotations: {e}")
        return None


def plot_unitig_pca(
    sample_id,
    sample_unitig_fraction,
    reference_data,
    blast_df,
    output_dir: Path,
    top_n_species=20
):
    """Plot unitig PCA loadings colored by top species in sample."""
    logger.info(f"\nGenerating unitig PCA plot for {sample_id}...")
    
    if blast_df is None or len(blast_df) == 0:
        logger.warning("  No BLAST annotations available - skipping unitig PCA")
        return
    
    # Get unitig loadings from PCA components
    # components shape: (n_components, n_features) = (50, 107480)
    # PC1 loadings = row 0, PC2 loadings = row 1
    pc1_loadings = reference_data['components'][0, :]
    pc2_loadings = reference_data['components'][1, :]
    unitig_ids = reference_data['unitig_ids']
    
    # Ensure unitig_ids is numpy array for indexing
    import numpy as np
    if not isinstance(unitig_ids, np.ndarray):
        unitig_ids = np.array(unitig_ids)
    
    logger.info(f"  PCA loadings: {len(pc1_loadings):,} unitigs")
    
    # Get sample's present unitigs (where fraction > 0)
    present_mask = sample_unitig_fraction > 0
    present_unitig_ids = unitig_ids[present_mask]
    present_fractions = sample_unitig_fraction[present_mask]
    
    logger.info(f"  Sample has {len(present_unitig_ids):,} present unitigs")
    
    if len(present_unitig_ids) == 0:
        logger.warning("  No present unitigs found")
        return
    
    # Filter BLAST to sample's present unitigs
    try:
        import polars as pl
        present_list = present_unitig_ids if isinstance(present_unitig_ids, list) else present_unitig_ids.tolist()
        sample_blast = blast_df.filter(pl.col('unitig_id').is_in(present_list))
    except:
        import pandas as pd
        if hasattr(blast_df, 'to_pandas'):
            blast_df = blast_df.to_pandas()
        sample_blast = blast_df[blast_df['unitig_id'].isin(present_unitig_ids)]
    
    if len(sample_blast) == 0:
        logger.warning("  No BLAST hits for sample's present unitigs")
        return
    
    logger.info(f"  BLAST hits for present unitigs: {len(sample_blast):,}")
    
    # Get unique taxids and resolve to species
    try:
        unique_taxids = sample_blast['taxid'].unique().to_list()
    except:
        unique_taxids = sample_blast['taxid'].unique().tolist()
    
    logger.info(f"  Resolving {len(unique_taxids)} unique taxids using taxonkit...")
    taxid_to_lineage = resolve_taxids(unique_taxids)
    logger.info(f"  ✓ Resolved {len(taxid_to_lineage)} taxids to lineages")
    
    if len(taxid_to_lineage) == 0:
        logger.warning("  No lineages resolved - check if taxonkit module is loaded")
        return
    
    # Convert to pandas for easier manipulation
    if hasattr(sample_blast, 'to_pandas'):
        sample_blast_pd = sample_blast.to_pandas()
    else:
        sample_blast_pd = sample_blast
    
    # Add lineages and extract species
    sample_blast_pd['lineage'] = sample_blast_pd['taxid'].map(taxid_to_lineage)
    sample_blast_pd['species'] = sample_blast_pd['lineage'].apply(extract_species_from_lineage)
    
    # Add fractions
    unitig_to_fraction = dict(zip(present_unitig_ids, present_fractions))
    sample_blast_pd['fraction'] = sample_blast_pd['unitig_id'].map(unitig_to_fraction)
    
    # Get top N species by total abundance
    species_abundance = sample_blast_pd.groupby('species')['fraction'].sum().sort_values(ascending=False)
    species_abundance = species_abundance[~species_abundance.index.str.contains('Unknown|unclassified', case=False, na=False)]
    top_species = species_abundance.head(top_n_species).index.tolist()
    
    logger.info(f"  Top {top_n_species} species by abundance:")
    for i, (sp, abundance) in enumerate(species_abundance.head(top_n_species).items(), 1):
        logger.info(f"    {i}. {sp}: {abundance:.4f}")
    
    # Filter to top species and keep best hit per unitig
    top_species_blast = sample_blast_pd[sample_blast_pd['species'].isin(top_species)].copy()
    top_species_blast = top_species_blast.sort_values('bitscore', ascending=False).drop_duplicates('unitig_id', keep='first')
    
    # Create loading dataframe for plotting
    import pandas as pd
    loading_df = pd.DataFrame({
        'unitig_id': unitig_ids,
        'PC1_loading': pc1_loadings,
        'PC2_loading': pc2_loadings
    })
    
    # Merge with species annotations
    plot_data = loading_df[loading_df['unitig_id'].isin(top_species_blast['unitig_id'])].copy()
    plot_data = plot_data.merge(
        top_species_blast[['unitig_id', 'species', 'fraction']], 
        on='unitig_id', 
        how='left'
    )
    
    logger.info(f"  Plotting {len(plot_data):,} unitigs from top {top_n_species} species")
    
    # Create plot
    fig = go.Figure()
    
    # Color palette
    colors = px.colors.qualitative.Vivid
    species_colors = {sp: colors[i % len(colors)] for i, sp in enumerate(top_species)}
    
    # Plot each species
    for species in top_species:
        species_data = plot_data[plot_data['species'] == species]
        
        if len(species_data) == 0:
            continue
        
        fig.add_trace(go.Scattergl(
            x=species_data['PC1_loading'],
            y=species_data['PC2_loading'],
            mode='markers',
            marker=dict(
                size=8,
                color=species_colors[species],
                opacity=0.9,
                line=dict(width=1, color='white')
            ),
            name=f'{species} ({len(species_data):,})',
            hovertemplate=f'<b>{species}</b><br>Unitig ID: %{{text}}<br>PC1: %{{x:.3f}}<br>PC2: %{{y:.3f}}<br>Abundance: %{{customdata:.4f}}<extra></extra>',
            text=species_data['unitig_id'],
            customdata=species_data['fraction'],
            showlegend=True
        ))
    
    fig.update_layout(
        title=f'Unitig PCA Loadings - {sample_id}<br><sub>Colored by Top {top_n_species} Species</sub>',
        xaxis_title='PC1 Loading',
        yaxis_title='PC2 Loading',
        template='plotly_white',
        width=1400,
        height=1000,
        font=dict(size=12),
        hovermode='closest',
        legend=dict(
            yanchor='top',
            y=0.99,
            xanchor='left',
            x=0.01,
            bgcolor='rgba(255,255,255,0.8)'
        )
    )
    
    # Save
    html_path = output_dir / f'pca_projection_unitigs_species.html'
    png_path = output_dir / f'pca_projection_unitigs_species.png'
    fig.write_html(str(html_path))
    try:
        fig.write_image(str(png_path), width=1400, height=1000)
        logger.info(f"  ✓ Saved: {html_path.name}, {png_path.name}")
    except Exception as e:
        logger.info(f"  ✓ Saved: {html_path.name}")
        if 'kaleido' in str(e).lower():
            logger.debug(f"    (PNG export requires kaleido package)")


def plot_species_abundance_barplot(
    sample_id,
    sample_unitig_fraction,
    reference_data,
    blast_df,
    output_dir: Path,
    top_n_species=20
):
    """Plot species abundance as percentage of unitigs."""
    logger.info(f"\nGenerating species abundance bar plot for {sample_id}...")
    
    if blast_df is None or len(blast_df) == 0:
        logger.warning("  No BLAST annotations available - skipping abundance plot")
        return
    
    unitig_ids = reference_data['unitig_ids']
    
    # Ensure unitig_ids is numpy array
    import numpy as np
    if not isinstance(unitig_ids, np.ndarray):
        unitig_ids = np.array(unitig_ids)
    
    # Get sample's present unitigs (where fraction > 0)
    present_mask = sample_unitig_fraction > 0
    present_unitig_ids = unitig_ids[present_mask]
    present_fractions = sample_unitig_fraction[present_mask]
    
    total_unitigs = len(unitig_ids)  # Total unitigs in feature space
    total_present_unitigs = len(present_unitig_ids)
    logger.info(f"  Total present unitigs: {total_present_unitigs:,} / {total_unitigs:,}")
    
    if total_present_unitigs == 0:
        logger.warning("  No present unitigs found")
        return
    
    # Filter BLAST to sample's present unitigs
    try:
        import polars as pl
        present_list = present_unitig_ids if isinstance(present_unitig_ids, list) else present_unitig_ids.tolist()
        sample_blast = blast_df.filter(pl.col('unitig_id').is_in(present_list))
    except:
        import pandas as pd
        if hasattr(blast_df, 'to_pandas'):
            blast_df_pd = blast_df.to_pandas()
        else:
            blast_df_pd = blast_df
        sample_blast = blast_df_pd[blast_df_pd['unitig_id'].isin(present_unitig_ids)]
    
    if len(sample_blast) == 0:
        logger.warning("  No BLAST hits for present unitigs")
        return
    
    # Get unique taxids and resolve to species
    try:
        unique_taxids = sample_blast['taxid'].unique().to_list()
    except:
        unique_taxids = sample_blast['taxid'].unique().tolist()
    
    logger.info(f"  Resolving {len(unique_taxids)} unique taxids...")
    taxid_to_lineage = resolve_taxids(unique_taxids)
    
    if len(taxid_to_lineage) == 0:
        logger.warning("  No lineages resolved")
        return
    
    # Convert to pandas for manipulation
    if hasattr(sample_blast, 'to_pandas'):
        sample_blast_pd = sample_blast.to_pandas()
    else:
        sample_blast_pd = sample_blast
    
    # Add lineages and extract species
    sample_blast_pd['lineage'] = sample_blast_pd['taxid'].map(taxid_to_lineage)
    sample_blast_pd['species'] = sample_blast_pd['lineage'].apply(extract_species_from_lineage)
    
    # Keep best hit per unitig (highest bitscore)
    sample_blast_pd = sample_blast_pd.sort_values('bitscore', ascending=False).drop_duplicates('unitig_id', keep='first')
    
    # Count unitigs per species
    species_counts = sample_blast_pd['species'].value_counts()
    
    # Remove Unknown/unclassified
    species_counts = species_counts[~species_counts.index.str.contains('Unknown|unclassified', case=False, na=False)]
    
    # Get top N species
    top_species_counts = species_counts.head(top_n_species)
    
    # Calculate percentages relative to TOTAL unitigs (not just present ones)
    percentages = (top_species_counts / total_unitigs * 100).round(2)
    
    logger.info(f"  Top {top_n_species} species by unitig count:")
    for i, (species, count) in enumerate(top_species_counts.items(), 1):
        pct = percentages[species]
        logger.info(f"    {i}. {species}: {int(count)} unitigs ({pct:.2f}%)")
    
    # Create bar plot
    import pandas as pd
    plot_df = pd.DataFrame({
        'Species': top_species_counts.index,
        'Count': top_species_counts.values,
        'Percentage': percentages.values
    })
    
    # Reverse for better display (highest at top)
    plot_df = plot_df.iloc[::-1]
    
    fig = go.Figure()
    
    # Use single teal color for bars
    fig.add_trace(go.Bar(
        y=plot_df['Species'],
        x=plot_df['Percentage'],
        orientation='h',
        text=plot_df['Percentage'].apply(lambda x: f'{x:.2f}%'),
        textposition='auto',
        marker=dict(color='teal'),
        hovertemplate='<b>%{y}</b><br>Unitigs: %{customdata}<br>Percentage: %{x:.2f}%<extra></extra>',
        customdata=plot_df['Count']
    ))
    
    fig.update_layout(
        title=f'Species Abundance - {sample_id}<br><sub>Top {top_n_species} Species by Unitig Count (% of {total_unitigs:,} total unitigs)</sub>',
        xaxis_title='Percentage of Total Unitigs (%)',
        yaxis_title='Species',
        template='plotly_white',
        width=1200,
        height=800,
        font=dict(size=11),
        margin=dict(l=250, r=50, t=100, b=50)
    )
    
    # Save
    html_path = output_dir / f'species_abundance.html'
    png_path = output_dir / f'species_abundance.png'
    fig.write_html(str(html_path))
    try:
        fig.write_image(str(png_path), width=1200, height=800)
        logger.info(f"  ✓ Saved: {html_path.name}, {png_path.name}")
    except Exception as e:
        logger.info(f"  ✓ Saved: {html_path.name}")
        if 'kaleido' in str(e).lower():
            logger.debug(f"    (PNG export requires kaleido package)")


def main():
    parser = argparse.ArgumentParser(
        description="DIANA Project: Project samples onto reference PCA space",
        prog="diana-project",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:
  # Single sample
  diana-project --sample results/validation_predictions/ERR10114862/
  
  # Multiple samples
  diana-project --sample results/validation_predictions/ERR*/
  
  # With custom output directory
  diana-project --sample results/validation_predictions/ERR10114862/ \\
                --output results/pca_projections/

This command requires that samples have already been processed by diana-predict.
It uses the existing unitig fraction files to project samples onto PCA space.
        """
    )
    parser.add_argument("--version", action="version",
                        version=f"%(prog)s {importlib.metadata.version('diana')}")

    # Input
    parser.add_argument(
        '--sample', '-s',
        type=str,
        nargs='+',
        required=True,
        help='Path(s) to diana-predict output directory(ies) (supports wildcards)'
    )
    
    # PCA reference
    parser.add_argument(
        '--pca-reference',
        type=Path,
        default=Path("models/pca_reference.pkl"),
        help='Path to PCA reference file (default: models/pca_reference.pkl)'
    )
    
    # Metadata
    parser.add_argument(
        '--metadata',
        type=Path,
        default=Path("paper/metadata/train_metadata.tsv"),
        help='Path to training metadata (default: paper/metadata/train_metadata.tsv)'
    )
    
    # Output
    parser.add_argument(
        '--output', '-o',
        type=Path,
        default=Path("results/pca_projection"),
        help='Output directory (default: results/pca_projection)'
    )
    
    # Neighbors
    parser.add_argument(
        '--k-neighbors',
        type=int,
        default=5,
        help='Number of nearest neighbors to highlight (default: 5)'
    )
    
    # Logging
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Enable verbose logging'
    )
    
    args = parser.parse_args()
    setup_logging(args.verbose)
    
    logger.info("=" * 70)
    logger.info("DIANA PROJECT: Project samples onto reference PCA space")
    logger.info("=" * 70)
    
    # Expand wildcards and collect all sample directories
    sample_dirs = []
    for pattern in args.sample:
        matches = glob(pattern)
        if not matches:
            logger.warning(f"No directories match pattern: {pattern}")
            continue
        for match in matches:
            match_path = Path(match)
            if match_path.is_dir():
                sample_dirs.append(match_path)
            else:
                logger.warning(f"Not a directory: {match}")
    
    if not sample_dirs:
        logger.error("No sample directories to process")
        sys.exit(1)
    
    logger.info(f"Found {len(sample_dirs)} sample(s) to project")
    
    # Load PCA reference (shared for all samples)
    logger.info("\n" + "=" * 70)
    logger.info("Loading reference PCA space")
    logger.info("=" * 70)
    
    reference_data = load_pca_reference(args.pca_reference)
    reference_pca = reference_data['pca_coordinates']
    reference_sample_ids = reference_data['sample_ids']
    
    # Load BLAST annotations (shared for all samples)
    blast_file = Path("results/feature_analysis/all_features_blast/blast_results.txt")
    blast_df = load_blast_annotations(blast_file, reference_data['unitig_ids'])
    if blast_df is None:
        logger.warning("\nBLAST annotations not available - unitig PCA plots will be skipped")
        logger.warning("To enable unitig plots, ensure BLAST results exist at:")
        logger.warning(f"  {blast_file}")
    
    # Load reference metadata
    if not args.metadata.exists():
        logger.error(f"Metadata not found: {args.metadata}")
        sys.exit(1)
    
    try:
        import polars as pl
        metadata = pl.read_csv(str(args.metadata), separator='\t')
        # Ensure sample order matches reference_sample_ids
        metadata = metadata.filter(pl.col('Run_accession').is_in(reference_sample_ids))
        metadata = metadata.sort(by='Run_accession')
    except ImportError:
        import pandas as pd
        metadata = pd.read_csv(args.metadata, sep='\t')
        metadata = metadata[metadata['Run_accession'].isin(reference_sample_ids)]
        metadata = metadata.sort_values('Run_accession').reset_index(drop=True)
    
    # Process each sample
    for i, sample_dir in enumerate(sample_dirs, 1):
        logger.info("\n" + "=" * 70)
        logger.info(f"Processing sample {i}/{len(sample_dirs)}: {sample_dir.name}")
        logger.info("=" * 70)
        
        try:
            # Load sample unitig vector
            unitig_vector, sample_id = load_sample_from_prediction_dir(sample_dir)
            
            # Load predictions if available
            predictions = load_predictions(sample_dir)
            if predictions:
                logger.info(f"  ✓ Loaded predictions from diana-predict")
            
            # Project onto PCA space
            sample_pca = project_sample(unitig_vector, reference_data, sample_id)
            
            # Find nearest neighbors
            nearest_ids, nearest_distances = compute_neighbors(
                sample_pca, 
                reference_pca, 
                reference_sample_ids,
                k=args.k_neighbors
            )
            
            logger.info(f"\n  Top {args.k_neighbors} nearest neighbors:")
            for j, (neighbor_id, distance) in enumerate(zip(nearest_ids, nearest_distances), 1):
                logger.info(f"    {j}. {neighbor_id} (distance: {distance:.2f})")
            
            # Generate plots
            sample_output_dir = args.output / sample_id
            plot_pca_projection(
                sample_pca=sample_pca,
                sample_id=sample_id,
                reference_pca=reference_pca,
                reference_sample_ids=reference_sample_ids,
                reference_metadata=metadata,
                output_dir=sample_output_dir,
                nearest_ids=nearest_ids,
                predictions=predictions
            )
            
            # Generate unitig PCA projection colored by species
            if blast_df is not None:
                plot_unitig_pca(
                    sample_id=sample_id,
                    sample_unitig_fraction=unitig_vector,
                    reference_data=reference_data,
                    blast_df=blast_df,
                    output_dir=sample_output_dir,
                    top_n_species=20
                )
                
                # Generate species abundance bar plot
                plot_species_abundance_barplot(
                    sample_id=sample_id,
                    sample_unitig_fraction=unitig_vector,
                    reference_data=reference_data,
                    blast_df=blast_df,
                    output_dir=sample_output_dir,
                    top_n_species=20
                )
            
            logger.info(f"\n  ✓ Results saved to: {sample_output_dir}")
            
        except Exception as e:
            logger.error(f"  ✗ Failed to process {sample_dir.name}: {e}")
            if args.verbose:
                import traceback
                traceback.print_exc()
            continue
    
    # Summary
    logger.info("\n" + "=" * 70)
    logger.info("PROJECTION COMPLETE")
    logger.info("=" * 70)
    logger.info(f"Processed: {len(sample_dirs)} sample(s)")
    logger.info(f"Output directory: {args.output}")
    logger.info("=" * 70)


if __name__ == "__main__":
    main()
