#!/usr/bin/env python3
"""
DIANA Project: Project samples onto reference PCA space.

This command visualizes where diana-predict samples fall in PCA space relative to 
training data. It uses the unitig fraction files already generated by diana-predict.

Usage:
    # Single sample
    diana-project --sample results/validation_predictions/ERR10114862/
    
    # Multiple samples
    diana-project --sample results/validation_predictions/ERR*/
"""

import argparse
import logging
import sys
from pathlib import Path
import json
from glob import glob
import plotly.graph_objects as go
import numpy as np
import pickle

logger = logging.getLogger(__name__)


def setup_logging(verbose=False):
    """Setup logging configuration."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )


def load_sample_from_prediction_dir(prediction_dir: Path) -> tuple[np.ndarray, str]:
    """
    Load unitig fraction vector from a diana-predict output directory.
    
    Args:
        prediction_dir: Path to diana-predict output directory
        
    Returns:
        (unitig_vector, sample_id)
    """
    prediction_dir = Path(prediction_dir)
    sample_id = prediction_dir.name
    
    # Find unitig fraction file
    unitig_fraction_file = prediction_dir / f"{sample_id}_unitig_fraction.txt"
    
    if not unitig_fraction_file.exists():
        raise FileNotFoundError(
            f"Unitig fraction file not found: {unitig_fraction_file}\n"
            f"Expected: {sample_id}_unitig_fraction.txt\n"
            f"This sample may not have been processed by diana-predict yet."
        )
    
    logger.info(f"Loading sample: {sample_id}")
    logger.debug(f"  From: {unitig_fraction_file}")
    
    # Load vector
    unitig_vector = np.loadtxt(unitig_fraction_file)
    logger.debug(f"  Vector shape: {unitig_vector.shape}")
    
    return unitig_vector, sample_id


def load_pca_reference(pca_reference_path: Path):
    """Load saved PCA model and reference data."""
    if not pca_reference_path.exists():
        logger.error(f"PCA reference not found: {pca_reference_path}")
        logger.error("")
        logger.error("Please generate PCA reference first:")
        logger.error("  python scripts/paper/06_generate_pca_analysis.py")
        raise FileNotFoundError(f"PCA reference not found: {pca_reference_path}")
    
    logger.info(f"Loading PCA reference: {pca_reference_path}")
    
    with open(pca_reference_path, 'rb') as f:
        reference_data = pickle.load(f)
    
    logger.info(f"  ✓ PCA components: {reference_data['pca_model'].n_components_}")
    logger.info(f"  ✓ Reference samples: {len(reference_data['sample_ids'])}")
    logger.info(f"  ✓ Features: {reference_data['n_features']} unitigs")
    
    return reference_data


def project_sample(unitig_vector: np.ndarray, reference_data: dict, sample_id: str):
    """Project sample onto reference PCA space."""
    logger.info(f"Projecting {sample_id} onto reference PCA space...")
    
    # Validate dimensions match
    if unitig_vector.shape[0] != reference_data['n_features']:
        raise ValueError(
            f"Feature dimension mismatch: sample has {unitig_vector.shape[0]} features, "
            f"reference expects {reference_data['n_features']}"
        )
    
    # Reshape to (1, n_features)
    sample_matrix = unitig_vector.reshape(1, -1)
    
    # Apply standardization if reference was standardized
    if reference_data.get('standardized', False) and 'scaler' in reference_data:
        logger.debug("  Applying standardization...")
        sample_matrix = reference_data['scaler'].transform(sample_matrix)
    
    # Project onto PCA space
    sample_pca = reference_data['pca_model'].transform(sample_matrix)
    logger.info(f"  ✓ Projected to {sample_pca.shape[1]}D PCA space")
    
    return sample_pca


def compute_neighbors(sample_pca, reference_pca, reference_sample_ids, k=5):
    """Find k nearest neighbors in PCA space."""
    from scipy.spatial.distance import cdist
    
    distances = cdist(sample_pca, reference_pca, metric='euclidean')[0]
    nearest_indices = np.argsort(distances)[:k]
    nearest_ids = [reference_sample_ids[i] for i in nearest_indices]
    nearest_distances = distances[nearest_indices]
    
    return nearest_ids, nearest_distances


def load_predictions(prediction_dir: Path):
    """Load diana-predict predictions if available."""
    prediction_file = prediction_dir / f"{prediction_dir.name}_predictions.json"
    
    if not prediction_file.exists():
        return None
    
    with open(prediction_file, 'r') as f:
        data = json.load(f)
    
    # Extract predictions in simplified format
    predictions = {}
    if 'predictions' in data:
        for task, task_data in data['predictions'].items():
            predictions[task] = {
                'label': task_data.get('predicted_class', 'Unknown'),
                'confidence': task_data.get('confidence', 0.0)
            }
    
    return predictions


def plot_pca_projection(
    sample_pca, 
    sample_id, 
    reference_pca, 
    reference_sample_ids,
    reference_metadata,
    output_dir: Path,
    nearest_ids=None,
    predictions=None
):
    """Create interactive PCA plot showing new sample and reference."""
    logger.info("Generating PCA projection plots...")
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create plots for each task
    tasks = ['sample_type', 'material', 'sample_host', 'community_type']
    
    for task in tasks:
        logger.info(f"  Creating plot for {task}...")
        
        fig = go.Figure()
        
        # Get reference labels (handle both polars and pandas)
        try:
            # Try polars first
            ref_labels = reference_metadata[task].to_list()
        except AttributeError:
            # Fall back to pandas
            ref_labels = reference_metadata[task].values
        
        ref_labels = np.array(ref_labels)
        unique_labels = sorted(list(set(ref_labels)))
        
        for label in unique_labels:
            mask = ref_labels == label
            indices = np.where(mask)[0]
            
            fig.add_trace(go.Scatter(
                x=reference_pca[indices, 0],
                y=reference_pca[indices, 1],
                mode='markers',
                name=label,
                marker=dict(size=5, opacity=0.6),
                text=[reference_sample_ids[i] for i in indices],
                hovertemplate='<b>%{text}</b><br>PC1: %{x:.2f}<br>PC2: %{y:.2f}<extra></extra>'
            ))
        
        # Highlight nearest neighbors if provided
        if nearest_ids:
            neighbor_indices = [i for i, sid in enumerate(reference_sample_ids) if sid in nearest_ids]
            # Get labels for nearest neighbors
            neighbor_labels = [ref_labels[i] for i in neighbor_indices]
            hover_texts = [
                f'<b>{reference_sample_ids[i]}</b><br>{task}: {ref_labels[i]}<br>PC1: {{x:.2f}}<br>PC2: {{y:.2f}}'
                for i in neighbor_indices
            ]
            fig.add_trace(go.Scatter(
                x=reference_pca[neighbor_indices, 0],
                y=reference_pca[neighbor_indices, 1],
                mode='markers',
                name='Nearest Neighbors',
                marker=dict(
                    size=12,
                    color='yellow',
                    symbol='diamond',
                    line=dict(width=2, color='black')
                ),
                text=[reference_sample_ids[i] for i in neighbor_indices],
                customdata=neighbor_labels,
                hovertemplate='<b>%{text}</b><br>' + task.replace('_', ' ').title() + ': %{customdata}<br>PC1: %{x:.2f}<br>PC2: %{y:.2f}<extra></extra>'
            ))
        
        # Plot new sample
        hover_text = f'<b>{sample_id}</b><br>PC1: %{{x:.2f}}<br>PC2: %{{y:.2f}}'
        if predictions and task in predictions:
            pred_label = predictions[task]['label']
            pred_conf = predictions[task]['confidence']
            hover_text += f'<br>Predicted: {pred_label} ({pred_conf:.1%})'
        hover_text += '<extra></extra>'
        
        fig.add_trace(go.Scatter(
            x=sample_pca[:, 0],
            y=sample_pca[:, 1],
            mode='markers',
            name=f'New Sample: {sample_id}',
            marker=dict(
                size=15,
                color='red',
                symbol='star',
                line=dict(width=2, color='black')
            ),
            hovertemplate=hover_text
        ))
        
        # Add title with prediction if available
        title = f'PCA Projection - {task.replace("_", " ").title()}'
        if predictions and task in predictions:
            pred_label = predictions[task]['label']
            pred_conf = predictions[task]['confidence']
            title += f'<br><sub>Predicted: {pred_label} (confidence: {pred_conf:.1%})</sub>'
        
        fig.update_layout(
            title=title,
            xaxis_title='PC1',
            yaxis_title='PC2',
            template='plotly_white',
            hovermode='closest',
            legend=dict(
                yanchor="top",
                y=0.99,
                xanchor="left",
                x=0.01,
                bgcolor="rgba(255,255,255,0.8)"
            ),
            width=1000,
            height=800
        )
        
        # Save
        html_path = output_dir / f'pca_projection_{task}.html'
        fig.write_html(str(html_path))
        logger.info(f"    ✓ Saved: {html_path.name}")


def main():
    parser = argparse.ArgumentParser(
        description="DIANA Project: Project samples onto reference PCA space",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:
  # Single sample
  diana-project --sample results/validation_predictions/ERR10114862/
  
  # Multiple samples
  diana-project --sample results/validation_predictions/ERR*/
  
  # With custom output directory
  diana-project --sample results/validation_predictions/ERR10114862/ \\
                --output results/pca_projections/

This command requires that samples have already been processed by diana-predict.
It uses the existing unitig fraction files to project samples onto PCA space.
        """
    )
    
    # Input
    parser.add_argument(
        '--sample', '-s',
        type=str,
        nargs='+',
        required=True,
        help='Path(s) to diana-predict output directory(ies) (supports wildcards)'
    )
    
    # PCA reference
    parser.add_argument(
        '--pca-reference',
        type=Path,
        default=Path("models/pca_reference.pkl"),
        help='Path to PCA reference file (default: models/pca_reference.pkl)'
    )
    
    # Metadata
    parser.add_argument(
        '--metadata',
        type=Path,
        default=Path("paper/metadata/train_metadata.tsv"),
        help='Path to training metadata (default: paper/metadata/train_metadata.tsv)'
    )
    
    # Output
    parser.add_argument(
        '--output', '-o',
        type=Path,
        default=Path("results/pca_projection"),
        help='Output directory (default: results/pca_projection)'
    )
    
    # Neighbors
    parser.add_argument(
        '--k-neighbors',
        type=int,
        default=5,
        help='Number of nearest neighbors to highlight (default: 5)'
    )
    
    # Logging
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Enable verbose logging'
    )
    
    args = parser.parse_args()
    setup_logging(args.verbose)
    
    logger.info("=" * 70)
    logger.info("DIANA PROJECT: Project samples onto reference PCA space")
    logger.info("=" * 70)
    
    # Expand wildcards and collect all sample directories
    sample_dirs = []
    for pattern in args.sample:
        matches = glob(pattern)
        if not matches:
            logger.warning(f"No directories match pattern: {pattern}")
            continue
        for match in matches:
            match_path = Path(match)
            if match_path.is_dir():
                sample_dirs.append(match_path)
            else:
                logger.warning(f"Not a directory: {match}")
    
    if not sample_dirs:
        logger.error("No sample directories to process")
        sys.exit(1)
    
    logger.info(f"Found {len(sample_dirs)} sample(s) to project")
    
    # Load PCA reference (shared for all samples)
    logger.info("\n" + "=" * 70)
    logger.info("Loading reference PCA space")
    logger.info("=" * 70)
    
    reference_data = load_pca_reference(args.pca_reference)
    reference_pca = reference_data['pca_coordinates']
    reference_sample_ids = reference_data['sample_ids']
    
    # Load reference metadata
    if not args.metadata.exists():
        logger.error(f"Metadata not found: {args.metadata}")
        sys.exit(1)
    
    try:
        import polars as pl
        metadata = pl.read_csv(str(args.metadata), separator='\t')
        # Ensure sample order matches reference_sample_ids
        metadata = metadata.filter(pl.col('Run_accession').is_in(reference_sample_ids))
        metadata = metadata.sort(by='Run_accession')
    except ImportError:
        import pandas as pd
        metadata = pd.read_csv(args.metadata, sep='\t')
        metadata = metadata[metadata['Run_accession'].isin(reference_sample_ids)]
        metadata = metadata.sort_values('Run_accession').reset_index(drop=True)
    
    # Process each sample
    for i, sample_dir in enumerate(sample_dirs, 1):
        logger.info("\n" + "=" * 70)
        logger.info(f"Processing sample {i}/{len(sample_dirs)}: {sample_dir.name}")
        logger.info("=" * 70)
        
        try:
            # Load sample unitig vector
            unitig_vector, sample_id = load_sample_from_prediction_dir(sample_dir)
            
            # Load predictions if available
            predictions = load_predictions(sample_dir)
            if predictions:
                logger.info(f"  ✓ Loaded predictions from diana-predict")
            
            # Project onto PCA space
            sample_pca = project_sample(unitig_vector, reference_data, sample_id)
            
            # Find nearest neighbors
            nearest_ids, nearest_distances = compute_neighbors(
                sample_pca, 
                reference_pca, 
                reference_sample_ids,
                k=args.k_neighbors
            )
            
            logger.info(f"\n  Top {args.k_neighbors} nearest neighbors:")
            for j, (neighbor_id, distance) in enumerate(zip(nearest_ids, nearest_distances), 1):
                logger.info(f"    {j}. {neighbor_id} (distance: {distance:.2f})")
            
            # Generate plots
            sample_output_dir = args.output / sample_id
            plot_pca_projection(
                sample_pca=sample_pca,
                sample_id=sample_id,
                reference_pca=reference_pca,
                reference_sample_ids=reference_sample_ids,
                reference_metadata=metadata,
                output_dir=sample_output_dir,
                nearest_ids=nearest_ids,
                predictions=predictions
            )
            
            logger.info(f"\n  ✓ Results saved to: {sample_output_dir}")
            
        except Exception as e:
            logger.error(f"  ✗ Failed to process {sample_dir.name}: {e}")
            if args.verbose:
                import traceback
                traceback.print_exc()
            continue
    
    # Summary
    logger.info("\n" + "=" * 70)
    logger.info("PROJECTION COMPLETE")
    logger.info("=" * 70)
    logger.info(f"Processed: {len(sample_dirs)} sample(s)")
    logger.info(f"Output directory: {args.output}")
    logger.info("=" * 70)


if __name__ == "__main__":
    main()
